### ISSUE TITLE
Configuration setup for executing the implementation

### ISSUE THREAD

**Issue by mrincs** [openai/pixel-cnn#18]
Here's an example setup I'm using to execute the program:

Python 3, Cuda 7.5, Tensorflow 0.11, #GPUs = 2

Everytime I'm hitting this error:
```
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    dropout_p=args.dropout_p, **model_opt)
...........
  File "/home/users/mrinmoy/Venv/p3-tf3-gpu/lib/python3.4/site-packages/tensorflow/python/framework/tensor_util.py", line 290, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got list containing Tensors of type '_Message' instead.

originally defined at:
  File "train.py", line 116, in <module>
    model = tf.make_template('model', model_spec)

```
Seems like its Tensorflow specific, but the authors did not mention any version dependency on Tensorflow. Any work around?

**Comment by mrincs** [comment]
Solved the issue. Its because Tensorflow version indeed. There's some migration change from 0.12 to 0.12+

Some changes in the code to make it work on previous versions:
1. Reverse the passed arguments in tf.concat()
2. Replace tf.where() with tf.select()
