### ISSUE TITLE
error while training 

### ISSUE THREAD

**Issue by ELHoussineT** [openai/pixel-cnn#26]
Hi, 

this is the error (first line is the run command) [images I use are jpg]: 

```
python3 train.py --data_dir=/path/to/my/images --save_dir=./
input args:
 {
    "max_epochs":5000,
    "num_samples":1,
    "dropout_p":0.5,
    "nr_gpu":8,
    "save_dir":"./",
    "save_interval":20,
    "seed":1,
    "data_set":"cifar",
    "data_dir":"/path/to/my/images",
    "nr_resnet":5,
    "nr_logistic_mix":10,
    "batch_size":16,
    "lr_decay":0.999995,
    "energy_distance":false,
    "class_conditional":false,
    "polyak_decay":0.9995,
    "resnet_nonlinearity":"concat_elu",
    "init_batch_size":16,
    "load_params":false,
    "learning_rate":0.001,
    "nr_filters":160
}
>> Downloading cifar-10-python.tar.gz 100.0%
Successfully downloaded cifar-10-python.tar.gz 170498071 bytes.
Traceback (most recent call last):
  File "train.py", line 103, in <module>
    init_pass = model(x_init, h_init, init=True, dropout_p=args.dropout_p, **model_opt)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 278, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/ubuntu/enhancer/pixel-cnn/pixel_cnn_pp/model.py", line 37, in model_spec
    u_list = [nn.down_shift(nn.down_shifted_conv2d(x_pad, num_filters=nr_filters, filter_size=[2, 3]))] # stream for pixels above
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/ubuntu/enhancer/pixel-cnn/pixel_cnn_pp/nn.py", line 303, in down_shifted_conv2d
    return conv2d(x, num_filters, filter_size=filter_size, pad='VALID', stride=stride, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/ubuntu/enhancer/pixel-cnn/pixel_cnn_pp/nn.py", line 210, in conv2d
    x = tf.nn.l2_normalize(x, axis=[0,1,2])
TypeError: l2_normalize() got an unexpected keyword argument 'axis'

originally defined at:
  File "train.py", line 100, in <module>
    model = tf.make_template('model', model_spec)

```

**Comment by savi429** [comment]
me to facing same error while using tf.make_template(), did you solved that issue ?
If anyone know how to fix that issue help me.

Thanks

**Comment by secina91** [comment]
Same problem here.

**Comment by aiscientist** [comment]
Version issue, use higher tf version such as 1.7
