### ISSUE TITLE
unexpected keyword argument 'keepdims'

### ISSUE THREAD

**Issue by RollTime12** [openai/pixel-cnn#29]
when running train.py i get the following issue:

C:\Users\cknau\Downloads\pixel-cnn-master\pixel-cnn-master>python train2.py
input args:
 {
    "data_dir":"D:\\PixelCNN\\dataset",
    "save_dir":"D:\\PixelCNN\\samples",
    "data_set":"cifar",
    "save_interval":20,
    "load_params":false,
    "nr_resnet":5,
    "nr_filters":160,
    "nr_logistic_mix":10,
    "resnet_nonlinearity":"concat_elu",
    "class_conditional":false,
    "energy_distance":false,
    "learning_rate":0.001,
    "lr_decay":0.999995,
    "batch_size":16,
    "init_batch_size":16,
    "dropout_p":0.5,
    "max_epochs":5000,
    "nr_gpu":8,
    "polyak_decay":0.9995,
    "num_samples":1,
    "seed":1
}
Traceback (most recent call last):
  File "train2.py", line 120, in <module>
    loss_gen.append(loss_fun(tf.stop_gradient(xs[i]), out))
  File "C:\Users\cknau\Downloads\pixel-cnn-master\pixel-cnn-master\pixel_cnn_pp\nn.py", line 83, in discretized_mix_logistic_loss
    log_probs = tf.reduce_sum(log_probs,3) + log_prob_from_logits(logit_probs)
  File "C:\Users\cknau\Downloads\pixel-cnn-master\pixel-cnn-master\pixel_cnn_pp\nn.py", line 27, in log_prob_from_logits
    m = tf.reduce_max(x, axis, keepdims=True)
TypeError: reduce_max() got an unexpected keyword argument 'keepdims'

Anyone know what's going on here. I have NumPy 1.13, so that's not the issue.

**Comment by xie9187** [comment]
Same problem with ubuntu 16.04 and tensorflow 1.4.1

**Comment by gorogoroyasu** [comment]
I got the same error, and I found that according to the TensorFlow docs, the option has to be `keep_dims` instead of `keepdims` in the latest version, and Tensorflow 1.4.1 also.

docs: https://www.tensorflow.org/api_docs/python/tf/reduce_sum
r1.4 branch code: https://github.com/tensorflow/tensorflow/blob/r1.4/tensorflow/python/ops/math_ops.py#L1263

**Comment by KevinZu** [comment]
@gorogoroyasu thank you!
